### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by benjaminprat** [Max9545/What-s-Cookin-Refactory#3]
review currents tests and decide what tests are still needed and if current tests cover both happy and sad paths.

**Comment by gaj23** [comment]
- [x] cookbook
- [x] cookbook-test

**Comment by gaj23** [comment]
- [x] recipe-test.js
- [x] recipe.js

**Comment by gaj23** [comment]
- [ ] ~~ pantry~~
- [ ] ~~pantry-js~~
Pantry has been removed as a part of the MVP.
